{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "9a22dd7f",
   "metadata": {},
   "source": [
    "MonReader\n",
    "This project developed an image classification model that detects whether a book page is flipping or not, helping MonReader determine the optimal moment to capture an image.\n",
    "\n",
    "The dataset was sourced from an AI and computer vision solutions provider that develops intelligent systems for tasks such as object recognition, motion detection, and visual data analysis.\n",
    "It consists of separate training and test sets stored in different folders. Exploratory Data Analysis (EDA) revealed that the images are in RGB format with full HD resolution (height = 1080, width = 1920). The training set contains 1,162 flip and 1,230 notflip images, while the test set contains 290 flip and 307 notflip images. \n",
    "\n",
    "#### Training Set Augumentation, Transformation and Split.\n",
    "The training set was augmented on the fly using RandomRotation(10), ColorJitter(brightness=0.2, contrast=0.2), and GaussianBlur(kernel_size=3). The images were then resized, converted to tensors, and normalized.\n",
    "The dataset was split into training (90%) and validation (10%) sets using a stratified sampling method.\n",
    "\n",
    "#### Model Training\n",
    "The model was trained using a transfer learning approach with a ResNet architecture as a fixed feature extractor. The backbone was frozen, and only the final classification layer was trained for binary classification. The model was optimized using the CrossEntropyLoss function and the Adam optimizer with a learning rate of 0.001. Training was conducted for 10 epochs with a batch size of 32.\n",
    "\n",
    "#### Trained Model Validation\n",
    "The trained model was evaluated on the validation set to monitor performance and generalization.\n",
    "\n",
    "#### Test set Transformation and validated model test.\n",
    "The test set was resized, converted to tensors, and normalized using the same preprocessing pipeline. The trained model was then evaluated on the test set.\n",
    "\n",
    "#### Model Evaluation\n",
    "The tesed model was evaluated using classification report model and the results are shown bellow.\n",
    "\n",
    "===== Training Set Classification Report =====\n",
    "              precision    recall  f1-score   support\n",
    "\n",
    "        flip       0.95      0.98      0.97      1045\n",
    "     notflip       0.98      0.95      0.97      1107\n",
    "\n",
    "    accuracy                           0.97      2152\n",
    "   macro avg       0.97      0.97      0.97      2152\n",
    "weighted avg       0.97      0.97      0.97      2152\n",
    "\n",
    "\n",
    "===== Training Set Confusion Matrix =====\n",
    "[[1028   17]\n",
    " [  53 1054]]\n",
    "\n",
    "\n",
    " ===== Validation Set Classification Report =====\n",
    "              precision    recall  f1-score   support\n",
    "\n",
    "        flip       0.97      0.97      0.97       117\n",
    "     notflip       0.98      0.98      0.98       123\n",
    "\n",
    "    accuracy                           0.97       240\n",
    "   macro avg       0.97      0.97      0.97       240\n",
    "weighted avg       0.97      0.97      0.97       240\n",
    "\n",
    "\n",
    "===== Validation Set Confusion Matrix =====\n",
    "[[114   3]\n",
    " [  3 120]]\n",
    "\n",
    "\n",
    "===== Test Set Classification Report =====\n",
    "              precision    recall  f1-score   support\n",
    "\n",
    "        flip       0.95      0.97      0.96       290\n",
    "     notflip       0.97      0.95      0.96       307\n",
    "\n",
    "    accuracy                           0.96       597\n",
    "   macro avg       0.96      0.96      0.96       597\n",
    "weighted avg       0.96      0.96      0.96       597\n",
    "\n",
    "\n",
    "===== Test Set Confusion Matrix =====\n",
    "[[280  10]\n",
    " [ 15 292]]\n",
    "\n",
    "#### Conclusion\n",
    "This project successfully developed an image classification model capable of detecting whether a book page is flipping or not. Using a transfer learning approach with a ResNet architecture as a fixed feature extractor, the model achieved high performance across training, validation, and test sets, with test f1-score reaching 96%.\n",
    "The consistent performance across all datasets indicates that the model generalizes well and is effective for real-world application in determining the optimal moment for image capture in the MonReader system.\n",
    "\n",
    "#### Recommendations.\n",
    "* Future work could involve fine-tuning the ResNet backbone by unfreezing selected layers to further improve classification performance.\n",
    "* Expanding the dataset with more diverse samples would enhance generalization, particularly under varying lighting and motion conditions.\n",
    "* Additional augmentation techniques and hyperparameter tuning could be explored to further optimize performance.\n",
    "* Incorporating real-time inference testing would help evaluate the model’s effectiveness in practical deployment scenarios."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
